import { EnergyDashboardChartConfig } from './energy-dashboard-chart-config';
export declare class EnergyDashboardChartCard extends HTMLElement {
    private _hass;
    config?: EnergyDashboardChartConfig;
    private _root;
    private _powerChartEl;
    private _energyChartEl;
    private _updateTimer;
    private _powerEntities;
    private _energyEntities;
    private _isLoading;
    private _apexChartCardRegistered;
    private _currentRefreshInterval;
    private _currentTimeRangeHours;
    private _viewMode;
    static get cardType(): string;
    static get displayName(): string;
    static get description(): string;
    static get icon(): string;
    constructor();
    private _loadViewMode;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private _handleViewModeChange;
    setConfig(config: Partial<EnergyDashboardChartConfig>): void;
    static getConfigElement(): HTMLElement;
    static getStubConfig(): {
        title: string;
        show_header: boolean;
        show_energy_section: boolean;
        chart_type?: string | undefined;
        chart_height?: number | undefined;
        show_points?: boolean | undefined;
        smooth_curve?: boolean | undefined;
        stroke_width?: number | undefined;
        update_interval?: number | undefined;
        hours_to_show?: number | undefined;
        aggregate_func?: string | undefined;
        power_chart_options?: {
            y_axis: import("./energy-dashboard-chart-config").ChartAxisOptions;
            x_axis?: import("./energy-dashboard-chart-config").ChartAxisOptions;
        } | undefined;
        energy_chart_options?: {
            y_axis: import("./energy-dashboard-chart-config").ChartAxisOptions;
            x_axis?: import("./energy-dashboard-chart-config").ChartAxisOptions;
        } | undefined;
        use_custom_colors?: boolean | undefined;
        show_legend?: boolean | undefined;
        show_state?: boolean | undefined;
        show_toggle?: boolean | undefined;
        auto_select_count?: number | undefined;
        max_height?: number | undefined;
        energy_auto_select_count?: number | undefined;
        persist_selection?: boolean | undefined;
        view_mode?: "power" | "energy" | undefined;
        entity_removal_filter?: string | undefined;
        refresh_rate?: "off" | "10s" | "30s" | undefined;
    };
    getCardSize(): number;
    set hass(hass: any);
    get hass(): any;
    private _loadSelectedEntities;
    private _startUpdateInterval;
    private _stopUpdateInterval;
    private _generateApexchartsConfig;
    private _createChart;
    private _createEmptyCard;
    private _createLoadingIndicator;
    private _createErrorMessage;
    private _updateCharts;
    private _renderSectionTitle;
    private _updateContent;
    private _checkApexChartsRegistration;
    private _setRefreshInterval;
    private _setTimeRange;
    private _manualRefresh;
    private _createRefreshControls;
    private _updateRefreshControlsUI;
    private _updateTimeRangeControlsUI;
    private _updateYAxisControlsUI;
    private _setYAxisMax;
}
